apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
      - name: wordpress-storage
        peristentVolumeClaim:
          claimName: wordpress-pvc-jegan # Replace 'jegan' with your name

      imagePullSecrets:
      - name: docker-pullsecret

      containers:
      - name: wordpress
        image: bitnami/wordpress:latest
        imagePullPolicy: IfNotPresent

        volumeMounts:
        - name: wordpress-storage
          mountPath: /bitnami/wordpress

        env:
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: username

        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: wordpress-secrets
              key: password

        - name: WORDPRESS_DATABASE_NAME
          valueFrom: 
             configMapKeyRef:
               name: wordpress-cm
               key: database_name


        - name: WORDPRESS_DATABASE_HOST
          valueFrom: 
            configMapKeyRef:
              name: wordpress-cm
              key: database_service_name

        - name: WORDPRESS_DATABASE_PORT_NUMBER
          valueFrom: 
            configMapKeyRef:
              name: wordpress-cm
              key: database_port

